language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/digitick.git"
  - secure: OrTok8XVivPYJV+FiGDDFunKiADr/jShIZgIqWwWA7xfgpLM7o7gvCJM7tHKxpWLMxUH4KuO47oPb1hJ4A3pSVxjIjHWM5NnkAXi5rzUnsFRuUvCcn9BIxtD82bzGOV/yVWmknt0/0kMGR5J4ZT+vze+v2AlUPJXcH8+s1CmMXi90UWVUvzA8/uLskKSUHwNNpHt/8dKClf1fNOTyxVPfFSJN0mYYGBTFvzI0zt4LBwMQ3d7NvlANek7xGRfPxl3TI6W4DFV7JsBR1lrHzj3S+hLgCKT60vBpjyfPnDeYv2SlfcN51XfRGUFAudtq1UtYvYJbfYNg2d1pZejAnfqQSy6bQIccfcN3huXef1D9Enrh1OXJTw659kULCuWrL4Z1veDacuv6gydi151b2TSrkmtNkUVW3kX9PK0m7LfkFu+VzvLjFGk5qciU2f4xSh1FGkEhYj3+RjcJiMqB63PvXvQJWSsNQlWB/1Y7tdRoqHyedQL7N4Qh//+0yW7OFj91I+lMgmvnugO8Ebrt/I3ZUdTRX87nUpMwFRc2rGghPPI3tyaK+RSxcGMF0UM9MGi/9UEgkPHhu61Ks56AxIZlfrlKbFPNapwhM6wykMTku/L5k+TPrfPoxM/whP5JAn9lUfw8Z8Tp43YIre5YUh8NjOeFrOCl/0Ne2TMQImBYu4=
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=latest yarn deploy
  on:
    branch: prod
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_da9dac2ea8e4_key -iv $encrypted_da9dac2ea8e4_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
